import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
    en: {
        welcome: 'Welcome back',
        dashboard: 'Dashboard',
        store: 'Store',
        missions: 'Missions',
        community: 'Community',
        leaderboard: 'Leaderboard',
        learning: 'Learning',
        quiz: 'Quiz',
        impact: 'Impact',
        sync: 'Sync',
        profile: 'Profile',
        manageMissions: 'Manage Missions',
        credits: 'Credits',
        transactionHistory: 'Transaction History',
        recentActivity: 'Your recent EcoCredit activity',
        currentBalance: 'Current Balance',
        noTransactions: 'No transactions yet',
        close: 'Close',
        logout: 'Logout',
        login: 'Sign In',
        register: 'Sign Up',
        email: 'Email',
        password: 'Password',
        name: 'Full Name',
        location: 'Location',
        crop: 'Main Crop',
        ecoScore: 'EcoScore',
        badges: 'Badges',
        streak: 'Day Streak',
        todayMission: "Today's Priority Mission",
        startMission: 'Start Mission',
        generateMission: 'Generate New Mission',
        myProfile: 'My Profile',
        myBadges: 'My Badges',
        verification: 'Verify'
    },
    hi: {
        welcome: 'वापस स्वागत है',
        dashboard: 'डैशबोर्ड',
        store: 'दुकान',
        missions: 'मिशन',
        community: 'समुदाय',
        leaderboard: 'लीडरबोर्ड',
        learning: 'सीखना',
        quiz: 'प्रश्नोत्तरी',
        impact: 'प्रभाव',
        sync: 'सिंक',
        profile: 'प्रोफ़ाइल',
        manageMissions: 'मिशन प्रबंधित करें',
        credits: 'क्रेडिट',
        transactionHistory: 'लेनदेन इतिहास',
        recentActivity: 'आपकी हालिया इको क्रेडिट गतिविधि',
        currentBalance: 'वर्तमान शेष',
        noTransactions: 'कोई लेनदेन नहीं',
        close: 'बंद करें',
        logout: 'लॉग आउट',
        login: 'साइन इन करें',
        register: 'साइन अप करें',
        email: 'ईमेल',
        password: 'पासवर्ड',
        name: 'पूरा नाम',
        location: 'स्थान',
        crop: 'मुख्य फसल',
        ecoScore: 'इको स्कोर',
        badges: 'बैज',
        streak: 'दिन की लकीर',
        todayMission: 'आज का प्राथमिकता मिशन',
        startMission: 'मिशन शुरू करें',
        generateMission: 'नया मिशन बनाएं',
        myProfile: 'मेरी प्रोफ़ाइल',
        myBadges: 'मेरे बैज',
        verification: 'सत्यापन'
    },
    mr: {
        welcome: 'परत स्वागत आहे',
        dashboard: 'डॅशबोर्ड',
        store: 'दुकान',
        missions: 'मिशन',
        community: 'समुदाय',
        leaderboard: 'लीडरबोर्ड',
        learning: 'शिक्षण',
        quiz: 'प्रश्नोत्तरी',
        impact: 'प्रभाव',
        sync: 'सिंक',
        profile: 'प्रोफाइल',
        manageMissions: 'मिशन व्यवस्थापित करा',
        credits: 'क्रेडिट',
        transactionHistory: 'व्यवहार इतिहास',
        recentActivity: 'तुमची अलीकडील इको क्रेडिट क्रियाकलाप',
        currentBalance: 'सध्याची शिल्लक',
        noTransactions: 'अद्याप कोणतेही व्यवहार नाहीत',
        close: 'बंद करा',
        logout: 'लॉग आउट',
        login: 'साइन इन करा',
        register: 'साइन अप करा',
        email: 'ईमेल',
        password: 'पासवर्ड',
        name: 'पूर्ण नाव',
        location: 'स्थान',
        crop: 'मुख्य पीक',
        ecoScore: 'इको स्कोर',
        badges: 'बॅज',
        streak: 'दिवसांची पट्टी',
        todayMission: 'आजचे प्राधान्य मिशन',
        startMission: 'मिशन सुरू करा',
        generateMission: 'नवीन मिशन तयार करा',
        myProfile: 'माझे प्रोफाइल',
        myBadges: 'माझे बॅज',
        verification: 'पडताळणी'
    },
    pa: {
        welcome: 'जी आउं नु',
        dashboard: 'डैशबोर्ड',
        store: 'ਸਟੋਰ',
        missions: 'ਮਿਸ਼ਨ',
        community: 'ਭਾਈਚਾਰਾ',
        leaderboard: 'ਲੀਡਰਬੋਰਡ',
        learning: 'ਸਿੱਖਣਾ',
        quiz: 'ਕਵਿਜ਼',
        impact: 'ਪ੍ਰਭਾਵ',
        sync: 'ਸਿੰਕ',
        profile: 'ਪ੍ਰੋਫਾਈਲ',
        manageMissions: 'ਮਿਸ਼ਨ ਪ੍ਰਬੰਧਿਤ ਕਰੋ',
        credits: 'ਕ੍ਰੈਡਿਟ',
        transactionHistory: 'ਲੈਣ-ਦੇਣ ਦਾ ਇਤਿਹਾਸ',
        recentActivity: 'ਤੁਹਾਡੀ ਹਾਲੀਆ ਈਕੋ ਕ੍ਰੈਡਿਟ ਗਤੀਵਿਧੀ',
        currentBalance: 'ਮੌਜੂਦਾ ਬਕਾਇਆ',
        noTransactions: 'ਅਜੇ ਕੋਈ ਲੈਣ-ਦੇਣ ਨਹੀਂ',
        close: 'ਬੰਦ ਕਰੋ',
        logout: 'ਲੌਗ ਆਉਟ',
        login: 'ਸਾਈਨ ਇਨ',
        register: 'ਰਜਿਸਟਰ',
        email: 'ਈਮੇਲ',
        password: 'ਪਾਸਵਰਡ',
        name: 'ਪੂਰਾ ਨਾਮ',
        location: 'ਸਥਾਨ',
        crop: 'ਮੁੱਖ ਫਸਲ',
        ecoScore: 'ਈਕੋ ਸਕੋਰ',
        badges: 'ਬੈਜ',
        streak: 'ਦਿਨ ਦੀ ਲਕੀਰ',
        todayMission: 'ਅੱਜ ਦਾ ਮਿਸ਼ਨ',
        startMission: 'ਮਿਸ਼ਨ ਸ਼ੁਰੂ ਕਰੋ',
        generateMission: 'ਨਵਾਂ ਮਿਸ਼ਨ ਬਣਾਓ',
        myProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
        myBadges: 'ਮੇਰੇ ਬੈਜ',
        verification: 'ਤਸਦੀਕ'
    },
    gu: {
        welcome: 'સ્વાગત છે',
        dashboard: 'ડેશબોર્ડ',
        store: 'દુકાન',
        missions: 'મિશન',
        community: 'સમુદાય',
        leaderboard: 'લીડરબોર્ડ',
        learning: 'શીખવું',
        quiz: 'ક્વિઝ',
        impact: 'અસર',
        sync: 'સિંક',
        profile: 'પ્રોફાઇલ',
        manageMissions: 'મિશન મેનેજ કરો',
        credits: 'ક્રેડિટ્સ',
        transactionHistory: 'વ્યવહાર ઇતિહાસ',
        recentActivity: 'તમારી તાજેતરની ઇકો ક્રેડિટ પ્રવૃત્તિ',
        currentBalance: 'વર્તમાન બેલેન્સ',
        noTransactions: 'હજુ સુધી કોઈ વ્યવહાર નથી',
        close: 'બંધ કરો',
        logout: 'લોગ આઉટ',
        login: 'સાઇન ઇન',
        register: 'રજીસ્ટર',
        email: 'ઇમેઇલ',
        password: 'પાસવર્ડ',
        name: 'પૂરું નામ',
        location: 'સ્થળ',
        crop: 'મુખ્ય પાક',
        ecoScore: 'ઇકો સ્કોર',
        badges: 'બેજેસ',
        streak: 'દિવસની સ્ટ્રીક',
        todayMission: 'આજનું મિશન',
        startMission: 'મિશન શરૂ કરો',
        generateMission: 'નવું મિશન બનાવો',
        myProfile: 'મારી પ્રોફાઇલ',
        myBadges: 'મારા બેજેસ',
        verification: 'ચકાસણી'
    },
    ta: {
        welcome: 'வரவேற்கிறோம்',
        dashboard: 'டாஷ்போர்டு',
        store: 'கடை',
        missions: 'பணிகள்',
        community: 'சமூகம்',
        leaderboard: 'லீடர்போர்டு',
        learning: 'கற்றல்',
        quiz: 'வினாடி வினா',
        impact: 'தாக்கம்',
        sync: 'ஒத்திசைவு',
        profile: 'சுயவிவரம்',
        manageMissions: 'பணிகளை நிர்வகி',
        credits: 'வரவுகள்',
        transactionHistory: 'பரிவர்த்தனை வரலாறு',
        recentActivity: 'உங்கள் சமீபத்திய செயல்பாடு',
        currentBalance: 'தற்போதைய இருப்பு',
        noTransactions: 'பரிவர்த்தனைகள் இல்லை',
        close: 'மூடு',
        logout: 'வெளியேறு',
        login: 'உள்நுழைய',
        register: 'பதிவு',
        email: 'மின்னஞ்சல்',
        password: 'கடவுச்சொல்',
        name: 'முழு பெயர்',
        location: 'இடம்',
        crop: 'முக்கிய பயிர்',
        ecoScore: 'சுற்றுச்சூழல் மதிப்பெண்',
        badges: 'பேட்ஜ்கள்',
        streak: 'தொடர் நாட்கள்',
        todayMission: 'இன்றைய பணி',
        startMission: 'பணியைத் தொடங்கு',
        generateMission: 'புதிய பணியை உருவாக்கு',
        myProfile: 'என் சுயவிவரம்',
        myBadges: 'என் பேட்ஜ்கள்',
        verification: 'சரிபார்ப்பு'
    },
    te: {
        welcome: 'స్వాగతం',
        dashboard: 'డ్యాష్‌బోర్డ్',
        store: 'స్టోర్',
        missions: 'మిషన్లు',
        community: 'సంఘం',
        leaderboard: 'లీడర్‌బోర్డ్',
        learning: 'నేర్చుకోవడం',
        quiz: 'క్విజ్',
        impact: 'ప్రభావం',
        sync: 'సింక్',
        profile: 'ప్రొఫైల్',
        manageMissions: 'మిషన్లను నిర్వహించండి',
        credits: 'క్రెడిట్స్',
        transactionHistory: 'లావాదేవీ చరిత్ర',
        recentActivity: 'మీ ఇటీవలి కార్యాచరణ',
        currentBalance: 'ప్రస్తుత బ్యాలెన్స్',
        noTransactions: 'లావాదేవీలు లేవు',
        close: 'మూసివేయు',
        logout: 'లాగ్ అవుట్',
        login: 'సైన్ ఇన్',
        register: 'నమోదు',
        email: 'ఇమెయిల్',
        password: 'పాస్‌వర్డ్',
        name: 'పూర్తి పేరు',
        location: 'స్థానం',
        crop: 'ప్రధాన పంట',
        ecoScore: 'ఎకో స్కోర్',
        badges: 'బ్యాడ్జ్‌లు',
        streak: 'రోజుల స్ట్రీక్',
        todayMission: 'నేటి మిషన్',
        startMission: 'మిషన్ ప్రారంభించు',
        generateMission: 'కొత్త మిషన్ సృష్టించు',
        myProfile: 'నా ప్రొఫైల్',
        myBadges: 'నా బ్యాడ్జ్‌లు',
        verification: 'ధృవీకరణ'
    },
    kn: {
        welcome: 'ಸ್ವಾಗತ',
        dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        store: 'ಅಂಗಡಿ',
        missions: 'ಮಿಷನ್‌ಗಳು',
        community: 'ಸಮುದಾಯ',
        leaderboard: 'ಲೀಡರ್‌ಬೋರ್ಡ್',
        learning: 'ಕಲಿಯುವಿಕೆ',
        quiz: 'ರಸಪ್ರಶ್ನೆ',
        impact: 'ಪ್ರಭಾವ',
        sync: 'ಸಿಂಕ್',
        profile: 'ಪ್ರೊಫೈಲ್',
        manageMissions: 'ಮಿಷನ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        credits: 'ಕ್ರೆಡಿಟ್ಸ್',
        transactionHistory: 'ವಹಿವಾಟು ಇತಿಹಾಸ',
        recentActivity: 'ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
        currentBalance: 'ಪ್ರಸ್ತುತ ಬಾಕಿ',
        noTransactions: 'ಯಾವುದೇ ವಹಿವಾಟುಗಳಿಲ್ಲ',
        close: 'ಮುಚ್ಚಿ',
        logout: 'ಲಾಗ್ ಔಟ್',
        login: 'ಸೈನ್ ಇನ್',
        register: 'ನೋಂದಣಿ',
        email: 'ಇಮೇಲ್',
        password: 'ಪಾಸ್‌ವರ್ಡ್',
        name: 'ಪೂರ್ಣ ಹೆಸರು',
        location: 'ಸ್ಥಳ',
        crop: 'ಮುಖ್ಯ ಬೆಳೆ',
        ecoScore: 'ಎಕೋ ಸ್ಕೋರ್',
        badges: 'ಬ್ಯಾಡ್ಜ್‌ಗಳು',
        streak: 'ದಿನದ ಸ್ಟ್ರೀಕ್',
        todayMission: 'ಇಂದಿನ ಮಿಷನ್',
        startMission: 'ಮಿಷನ್ ಪ್ರಾರಂಭಿಸಿ',
        generateMission: 'ಹೊಸ ಮಿಷನ್ ರಚಿಸಿ',
        myProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
        myBadges: 'ನನ್ನ ಬ್ಯಾಡ್ಜ್‌ಗಳು',
        verification: 'ಪರಿಶೀಲನೆ'
    },
    ml: {
        welcome: 'സ്വാഗതം',
        dashboard: 'ഡാഷ്ബോർഡ്',
        store: 'സ്റ്റോർ',
        missions: 'ദൗത്യങ്ങൾ',
        community: 'കമ്മ്യൂണിറ്റി',
        leaderboard: 'ലീഡർബോർഡ്',
        learning: 'പഠനം',
        quiz: 'ക്വിസ്',
        impact: 'ആഘാതം',
        sync: 'സിങ്ക്',
        profile: 'പ്രൊഫൈൽ',
        manageMissions: 'ദൗത്യങ്ങൾ നിയന്ത്രിക്കുക',
        credits: 'ക്രെഡിറ്റുകൾ',
        transactionHistory: 'ഇടപാട് ചരിത്രം',
        recentActivity: 'നിങ്ങളുടെ സമീപകാല പ്രവർത്തനം',
        currentBalance: 'നിലവിലെ ബാലൻസ്',
        noTransactions: 'ഇടപാടുകളൊന്നുമില്ല',
        close: 'അടയ്ക്കുക',
        logout: 'ലോഗ് ഔട്ട്',
        login: 'സൈൻ ഇൻ',
        register: 'രജിസ്റ്റർ',
        email: 'ഇമെയിൽ',
        password: 'പാസ്‌വേഡ്',
        name: 'മുഴുവൻ പേര്',
        location: 'സ്ഥലം',
        crop: 'പ്രധാന വിള',
        ecoScore: 'ഇക്കോ സ്കോർ',
        badges: 'ബാഡ്ജുകൾ',
        streak: 'സ്ട്രീക്ക്',
        todayMission: 'ഇന്നത്തെ ദൗത്യം',
        startMission: 'ദൗത്യം ആരംഭിക്കുക',
        generateMission: 'പുതിയ ദൗത്യം',
        myProfile: 'എന്റെ പ്രൊഫൈൽ',
        myBadges: 'എന്റെ ബാഡ്ജുകൾ',
        verification: 'പരിശോധന'
    },
    bn: {
        welcome: 'স্বাগতম',
        dashboard: 'ড্যাশবোর্ড',
        store: 'দোকান',
        missions: 'মিশন',
        community: 'সম্প্রদায়',
        leaderboard: 'লিডারবোর্ড',
        learning: 'শিক্ষা',
        quiz: 'কুইজ',
        impact: 'প্রভাব',
        sync: 'সিঙ্ক',
        profile: 'প্রোফাইল',
        manageMissions: 'মিশন পরিচালনা',
        credits: 'ক্রেডিট',
        transactionHistory: 'লেনদেনের ইতিহাস',
        recentActivity: 'আপনার সাম্প্রতিক কার্যকলাপ',
        currentBalance: 'বর্তমান ব্যালেন্স',
        noTransactions: 'কোন লেনদেন নেই',
        close: 'বন্ধ করুন',
        logout: 'লগ আউট',
        login: 'সাইন ইন',
        register: 'নিবন্ধন',
        email: 'ইমেল',
        password: 'পাসওয়ার্ড',
        name: 'পুরো নাম',
        location: 'অবস্থান',
        crop: 'প্রধান ফসল',
        ecoScore: 'ইকো স্কোর',
        badges: 'ব্যাজ',
        streak: 'ধারাবাহিকতা',
        todayMission: 'আজকের মিশন',
        startMission: 'মিশন শুরু করুন',
        generateMission: 'নতুন মিশন তৈরি করুন',
        myProfile: 'আমার প্রোফাইল',
        myBadges: 'আমার ব্যাজ',
        verification: 'যাচাইকরণ'
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('language') || 'en';
        setLanguage(savedLang);
    }, []);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
